# Generated by Django 3.2.4 on 2021-11-12 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer', models.CharField(max_length=5)),
                ('description', models.TextField()),
                ('password', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RollingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rolling_name', models.CharField(max_length=11)),
                ('recipient_name', models.CharField(max_length=5)),
                ('code', models.CharField(max_length=6)),
            ],
        ),
    ]
