# Generated by Django 3.2.4 on 2021-11-12 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rollingPaper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rollinginfo',
            name='rolling_name',
            field=models.CharField(max_length=15),
        ),
    ]
