# Generated by Django 3.2.3 on 2021-11-12 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rollingPaper', '0004_alter_rollinginfo_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='password',
            field=models.IntegerField(),
        ),
    ]
