# Generated by Django 3.2.3 on 2021-11-12 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rollingPaper', '0006_alter_rollinginfo_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rollinginfo',
            name='comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='rolling',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='rollingPaper.rollinginfo'),
        ),
    ]
