# Generated by Django 3.2.3 on 2021-11-12 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rollingPaper', '0009_alter_rollinginfo_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='description',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='password',
            field=models.IntegerField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='writer',
            field=models.CharField(default='', max_length=5, null=True),
        ),
    ]
